### ISSUE TITLE
请问网卡用的是什么？ 并且为什么换回 FakeSMC, 谢谢

### ISSUE THREAD

**Issue by theFool32** [youngle316/ASRock-Z370M-ITX-AC#1]

**Comment by youngle316** [comment]
网卡是 BCM94352Z。驱动方式可以看黑果小兵的[教程](https://blog.daliansky.net/Broadcom-BCM94352z-DW1560-drive-new-posture.html)
换回FakeSMC是为了使用HWMonitor，通过传感器来看硬件的信息，包括温度，转速，功耗等。
