### ISSUE TITLE
USB问题

### ISSUE THREAD

**Issue by hanxi2719** [youngle316/ASRock-Z370M-ITX-AC#10]
请教下，机箱的USB3可以使用吗？我的不行，温度传感器部分显示不全，使用HW monitor的话，不知道你这边是不是也是这样，感谢回答

**Comment by youngle316** [comment]
![image](https://user-images.githubusercontent.com/38031149/74604188-6717a080-50f6-11ea-9900-5fbab13ae4d0.png)
机箱的USB3.0是可以的。可以按这篇文章适配你自己的[USB3.0](https://younglele.cn/use-hackintool-custom-made-usb3.0/)
温度传感器很久之前都不用了，感觉用处不是很大。记得之前应该是显示全的。
