### ISSUE TITLE
加入EmuVariableUefi-64.efi之后iMessage能用了，但是每次开机都提示非正常重启

### ISSUE THREAD

**Issue by magicshine888** [youngle316/ASRock-Z370M-ITX-AC#11]
加入EmuVariableUefi-64.efi之后iMessage能用了，但是每次开机都提示非正常重启，一样都主板，请问大佬有遇到同样都问题吗

**Comment by youngle316** [comment]
没有碰到过这个问题

**Comment by caifeng250** [comment]
我没加入EmuVariableUefi-64.efi测试也可以用iMessage。
EmuVariableUefi-64.efi加了之后clover无法自动记住上次启动的磁盘
建议WhateverGreen升到1.3.7版本以上，不然BIOS开了iGPU会无法进入系统

**Comment by youngle316** [comment]
试了一下，删除EmuVariableUefi-64.efi确实可以用iMessage和接力等。下次更新的时候添加一下。👍

**Comment by magicshine888** [comment]
开始不能用iMessage，无论如何都不能用，加了EmuVariableUefi-64.efi之后iMessage正常了，但是开机提示非正常开机，之后删了EmuVariableUefi-64.efi不提示了，iMessage也能用

**Comment by youngle316** [comment]
问题已修复
