### ISSUE TITLE
有线网卡,怎么配置

### ISSUE THREAD

**Issue by jimmyqin** [youngle316/ASRock-Z370M-ITX-AC#16]
机型:i58400 z370-p  UHD630 , 没有无线网卡硬件, 有线的要怎么弄呢,小白一个.

**Comment by youngle316** [comment]
OC里有有线网卡的驱动，系统装好了插上网线可以直接上网的

**Comment by fabiusx** [comment]
Hi I have your same hardware and the latest version of BigSur, I tried different solutions to get Bluetooth to work but I couldn't. I also tried to copy all the efi but same result.
