### ISSUE TITLE
大佬你确定config.plist没有传错咩

### ISSUE THREAD

**Issue by zocoxx** [youngle316/ASRock-Z370M-ITX-AC#3]
用你这个EFI，开机直接报错，用CC看了下config.plist文件，发现ig-platform-id啥的都没有填，是不需要这个了咩

**Comment by youngle316** [comment]
用CC看是看不到的，用Hackintool可以看到的。那你用我最新的上传的EFI试试。

**Comment by zocoxx** [comment]
重新下载了，有用了，感谢大佬的分享，以后有更新就看你了

**Comment by zocoxx** [comment]
搞错了，测试的时候用的是我本身之前的EFI，你分享的这个EFI写到U盘之后启动还是会死机自动重启，用CC打开还是没办法看到相关信息

**Comment by youngle316** [comment]
自动重启前的报错信息是什么，有吗？

**Comment by zocoxx** [comment]
没加-v，进度条走到一半就自动重启了，也没有禁行标志

**Comment by youngle316** [comment]
那你在苹果启动盘上按下空格，选择-v和do not reboot on panic。然后回车 boot macos with selected options。看有什么问题。我不一定知道问题所在，我也是看别的大佬提供的EFI修改后以适合自己 。
![clover](https://user-images.githubusercontent.com/38031149/64789554-22b43180-d5a7-11e9-8275-9a04abc253e4.jpg)

**Comment by zocoxx** [comment]
借着你更新EFI的机会，我重新试了下，开机到这里就不动了
![11571190382_ pic](https://user-images.githubusercontent.com/24447169/66881560-d28f1b80-eff9-11e9-92ea-f8d88e8317c5.jpg)
![21571190383_ pic](https://user-images.githubusercontent.com/24447169/66881562-d458df00-eff9-11e9-8100-adda541581eb.jpg)
