### ISSUE TITLE
大神，机箱用的那款？

### ISSUE THREAD

**Issue by CharlesSong** [youngle316/ASRock-Z370M-ITX-AC#5]
我是小白，想diy自己的第一台黑苹果。我想入手
1.[deskmin gtx+z370版](https://detail.tmall.com/item.htm?id=605708391354&spm=a1z2k.11010449.931864.18.6016509dTxSD4p&scm=1007.13982.82927.0&last_time=1575117686&skuId=4411155946385)
2.i8500 cup
3.金士顿16G内存
等，是否可以完美？

**Comment by youngle316** [comment]
机箱都可以吧，没什么特殊要求。N卡在10.13.6之后就用不了。可以换Rx590或者580都可以。
你可以看[远景论坛](http://bbs.pcbeta.com/forum-561-1.html)上有很多配置，里面有很多大佬。没邀请码可以某宝6块买一个。

**Comment by xuatxl** [comment]
我看到你的590在10.15.2可以看4k也可以硬件加速，我在10.15.2只能fcpx可以硬件加速，视频就不行，我也是590可以加你qq问个问题吗        我qq 1786525357
